Repository apache/inlong-website, pull requests merged in 2021-12, with the labels that each got.

#206 [INLONG-205]Add a space between the URL and Chines period.
  i18n/zh-CN/docusaurus-plugin-content-docs-development/current/how-to-vote-a-committer-ppmc.md
Labels: bug, documentation

#211 [INLONG-1865][Improve] There are several errors in TubeMQ's guidance document
  i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/quick_start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.11.0/modules/tubemq/quick_start.md
Labels: documentation

#215 [INLONG-1919] fix TubeMQ HTTP API xls can not download
  docs/modules/tubemq/http_access_api.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/http_access_api.md
  i18n/zh-CN/docusaurus-plugin-content-docs/version-0.11.0/modules/tubemq/http_access_api.md
  versioned_docs/version-0.11.0/modules/tubemq/http_access_api.md
Labels: bug, documentation

#217 [INLONG-216] Optimize the documentation of TubeMQ
  docs/modules/tubemq/configure_introduction.md
  docs/modules/tubemq/console_introduction.md
  docs/modules/tubemq/error_code.md
  docs/modules/tubemq/quick_start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/configure_introduction.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/console_introduction.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/error_code.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/quick_start.md
Labels: documentation

#219 [INLONG-218]Add Metric documents of TubeMQ
  docs/modules/tubemq/tubemq_metrics.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/tubemq_metrics.md
Labels: documentation

#221 [INLONG-1939] add basic concepts for InLong
  docs/design_and_concept/basic_concept.md
  docs/modules/agent/file.md
  docs/modules/agent/overview.md
  docs/quick_start/hive_example.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/basic_concept.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/file.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/hive_example.md
  static/img/inlong_architecture.png
Labels: documentation

#228 [INLONG-1660][WebSite] translate how-to-release to english
  development/how-to-release.md
Labels: documentation

#227 [INLONG-1712][Agent][Docs] Add agent prometheus metrics doc
  docs/modules/agent/overview.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/overview.md
Labels: documentation

#229 [INLONG-2017] Add more guide documents for Pulsar
  docs/deployment/bare_metal.md
  docs/modules/manager/quick_start.md
  docs/user_guide/user_manual.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/bare_metal.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/quick_start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/user_guide/user_manual.md
Labels: documentation

#230 [INLONG-2029] add pulsar example document for the InLong
  docs/quick_start/hive_example.md
  docs/quick_start/img/pulsar-arch.png
  docs/quick_start/img/pulsar-data.png
  docs/quick_start/img/pulsar-group.png
  docs/quick_start/img/pulsar-hive.png
  docs/quick_start/img/pulsar-stream.png
  docs/quick_start/img/pulsar-topic.png
  docs/quick_start/pulsar_example.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/hive_example.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/img/pulsar-arch.png
  i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/img/pulsar-data.png
  i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/img/pulsar-group.png
  i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/img/pulsar-hive.png
  i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/img/pulsar-stream.png
  i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/img/pulsar-topic.png
  i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/pulsar_example.md
Labels: documentation

#231 [INLONG-2034] Update the definition of InLong more clearly
  docs/introduction.md
  src/pages/Home/config.json
Labels: documentation

#233 [INLONG-2042] fix the deployment guide mistakes
  docs/modules/dataproxy/quick_start.md
  docs/modules/manager/quick_start.md
  docs/modules/sort/quick_start.md
  docs/modules/tubemq/tubemq-manager/quick_start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/quick_start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/quick_start.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/tubemq-manager/quick_start.md
Labels: documentation

#236 [INLONG-234] Update peaceiris/actions-gh-pages version
  .github/workflows/deploy.yml
Labels: bug

#238 [INLONG-WEBSITE-237]Fix incorrect KEYS links in release template
  development/how-to-release.md
  i18n/zh-CN/docusaurus-plugin-content-docs-development/current/how-to-release.md
Labels: bug

#243 [INLONG-1945]Modify download&release notes for 0.12.0
  download/main.md
  download/release-0.10.0.md
  download/release-0.11.0.md
  download/release-0.12.0.md
  i18n/zh-CN/docusaurus-plugin-content-docs-download/current/main.md
  i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.10.0.md
  i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.11.0.md
  i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.12.0.md
Labels: documentation
